# Buck-lab router overrides.

ctrl:
  endpoint: ziti-controller-ctrl.ziti.svc:443

edge:
  advertisedHost: ziti-router.focuspass.com

linkListeners:
  transport:
    advertisedHost: ziti-router.focuspass.com

persistence:
  storageClass: longhorn-r2

image:
  repository: harbor.focuscell.org/openziti/ziti-router
  tag: "1.7.2"

nodeSelector:
  om-labs.io/storage-node: "true"

imagePullSecrets:
  - name: harbor-pull-secret
