apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-proxy-identity
  namespace: ziti
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: backup-proxy-identity
    creationPolicy: Owner
  data:
    - secretKey: backup-proxy.json
      remoteRef:
        key: ziti-identity-backup-proxy
